name: SomeHooks CI
on:
  push:
    branches: [ from_piper ]
  pull_request:
    branches: [ from_piper ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup dependencies
        run: npm install
      - name: Format code
        run: npm run lint
      - name: Run Tests
        run: npm test